// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://insaocskhnmgdvxcwpsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imluc2FvY3NraG5tZ2R2eGN3cHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTU3MjAsImV4cCI6MjA2MTE5MTcyMH0.nVDXiwovLyIbIub_Na4odYc5jgoBGcTOf8vVJCr4Iik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);